  FROM python:latest

  ENV PYTHONUNBUFFERED 1
  ENV PYTHONDONTWRITEBYTECODE 1

  WORKDIR /a2

  COPY requirements.txt /a2

  RUN pip install --no-cache-dir -r requirements.txt
  COPY . /a2

  EXPOSE 8080

  CMD python manage.py runserver 0.0.0.0:8080

