# Generated by Django 4.1 on 2023-05-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('timezone', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('etd', models.DateTimeField()),
                ('eta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('tail_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlaneModel',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('range', models.IntegerField()),
                ('takeoff_distance', models.IntegerField()),
                ('landing_distance', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('eng_desc', models.CharField(max_length=30)),
                ('max_altitude', models.IntegerField()),
                ('description', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_airport', to='dairy_flat_airways.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_airport', to='dairy_flat_airways.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('passport_number', models.CharField(max_length=30)),
                ('passport_expiry', models.DateField()),
                ('passport_country', models.CharField(max_length=30)),
                ('passport_issue', models.DateField()),
                ('passport_issue_country', models.CharField(max_length=30)),
                ('passport_issue_city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.users')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('schedule', models.DateTimeField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.plane')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.route')),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.planemodel'),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.plane'),
        ),
    ]
