# Generated by Django 4.1 on 2023-05-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='plane',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='model',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='route',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Plane',
        ),
        migrations.DeleteModel(
            name='PlaneModel',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
