# Generated by Django 4.1 on 2023-05-30 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='origin',
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_airport', to='dairy_flat_airways.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_airport', to='dairy_flat_airways.airport')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='RouteLeg_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.routeleg'),
            preserve_default=False,
        ),
    ]
