# Generated by Django 4.1 on 2023-05-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0004_remove_route_destination_remove_route_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule',
            new_name='schedule_etd',
        ),
    ]
