# Generated by Django 4.1 on 2023-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0005_rename_schedule_schedule_schedule_etd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_etd',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(default='{"Schedule":NULL}', max_length=254),
            preserve_default=False,
        ),
    ]
