# Generated by Django 4.1 on 2023-05-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0006_remove_schedule_schedule_etd_schedule_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='RouteLeg_id',
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='Name', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RouteToLeg',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('RouteLeg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.routeleg')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.route')),
            ],
        ),
    ]
