# Generated by Django 4.1 on 2023-05-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0008_alter_planemodel_id_alter_route_id_alter_routeleg_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='plane',
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.route'),
            preserve_default=False,
        ),
    ]
