# Generated by Django 4.1 on 2023-05-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0009_remove_flight_plane_flight_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='eta',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='etd',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='route',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default='NZNE', on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='dairy_flat_airways.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='eta_destination',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='eta_stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='etd_origin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='etd_stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(default='NZRO', on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='dairy_flat_airways.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='stopover',
            field=models.ForeignKey(default='NZNO', on_delete=django.db.models.deletion.PROTECT, related_name='stopover', to='dairy_flat_airways.airport'),
            preserve_default=False,
        ),
    ]
