# Generated by Django 4.1 on 2023-05-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0012_remove_flight_id_alter_flight_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
    ]
