# Generated by Django 4.1 on 2023-05-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0016_flight_plane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='eta_destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='eta_stop',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='etd_stop',
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.route'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='stopover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stopover', to='dairy_flat_airways.airport'),
        ),
    ]
