# Generated by Django 4.1 on 2023-05-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0017_remove_flight_eta_destination_remove_flight_eta_stop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='stopover',
        ),
    ]
