# Generated by Django 4.1 on 2023-05-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0018_remove_flight_destination_remove_flight_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='route_details',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routeleg',
            name='route_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.route'),
            preserve_default=False,
        ),
    ]
