# Generated by Django 4.1 on 2023-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0019_flight_route_details_routeleg_route_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routetoleg',
            name='RouteLeg',
        ),
        migrations.RemoveField(
            model_name='routetoleg',
            name='route',
        ),
        migrations.AlterField(
            model_name='routetoleg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
