# Generated by Django 4.1 on 2023-06-05 04:59

import dairy_flat_airways.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0020_remove_routetoleg_routeleg_remove_routetoleg_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(default=dairy_flat_airways.models.FlightStatus['SCHEDULED'], max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default=dairy_flat_airways.models.TicketStatus['SCHEDULED'], max_length=30),
        ),
    ]
