# Generated by Django 4.1 on 2023-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0024_alter_flight_status_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='etd_origin',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='plane',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='route',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='route_details',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='status',
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
