# Generated by Django 4.1 on 2023-06-05 09:53

import dairy_flat_airways.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0025_remove_flight_etd_origin_remove_flight_flight_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='etd_origin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='DFA-1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(default='SYJ30', on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.plane'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dairy_flat_airways.route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='route_details',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[(dairy_flat_airways.models.FlightStatus['SCHEDULED'], 0), (dairy_flat_airways.models.FlightStatus['GO_TO_GATE'], 1), (dairy_flat_airways.models.FlightStatus['BOARDED'], 2), (dairy_flat_airways.models.FlightStatus['IN_FLIGHT'], 3), (dairy_flat_airways.models.FlightStatus['COMPLETED'], 4), (dairy_flat_airways.models.FlightStatus['CANCELLED'], 5), (dairy_flat_airways.models.FlightStatus['DELAYED'], 6), (dairy_flat_airways.models.FlightStatus['DIVERTED'], 7), (dairy_flat_airways.models.FlightStatus['UNKNOWN'], 8), (dairy_flat_airways.models.FlightStatus['ATLAYOVER'], 9)], default=dairy_flat_airways.models.FlightStatus['SCHEDULED'], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
