# Generated by Django 4.1 on 2023-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0029_ticket_legs_alter_flight_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeleg',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
