# Generated by Django 4.1 on 2023-06-11 00:00

import dairy_flat_airways.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0030_routeleg_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(default='default@default.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(default='Dummy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='Dummy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='passengers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=enumfields.fields.EnumField(default='Draft', enum=dairy_flat_airways.models.TicketStatus, max_length=10),
        ),
    ]
