# Generated by Django 4.1 on 2023-06-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_flat_airways', '0031_remove_ticket_flight_remove_ticket_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner_email',
            field=models.EmailField(default='default@default.com', max_length=254),
            preserve_default=False,
        ),
    ]
